# Generated by Django 6.1 on 2026-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('programming', 'Linguagens de Programação'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Bancos de Dados'), ('devops', 'DevOps & Cloud'), ('mobile', 'Mobile & Ferramentas')], max_length=20),
        ),
    ]
