# Generated by Django 6.1 on 2026-09-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_technology_userprofile_location_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Ex: devicon-python-plain colored', max_length=100),
        ),
    ]
