# Generated by Django 6.1 on 2026-09-30 11:13

from django.db import migrations
from django.db import migrations

DATA = {
    "programming": [
        ("JavaScript", "javascript-plain"), ("TypeScript", "typescript-plain"),
        ("Python", "python-plain"), ("Java", "java-plain"),
        ("C++", "cplusplus-plain"), ("C#", "csharp-plain"), ("PHP", "php-plain"),
        ("Go", "go-original-wordmark"), ("Rust", "rust-plain"),
        ("Ruby", "ruby-plain"), ("Kotlin", "kotlin-plain"),
    ],
    "frontend": [
        ("HTML5", "html5-plain"), ("CSS3", "css3-plain"), ("React", "react-original"),
        ("Vue.js", "vuejs-plain"), ("Angular", "angularjs-plain"),
        ("Next.js", "nextjs-plain"), ("Svelte", "svelte-plain"),
        ("Tailwind CSS", "tailwindcss-plain"), ("Bootstrap", "bootstrap-plain"),
        ("Sass", "sass-original"),
    ],
    "backend": [
        ("Node.js", "nodejs-plain"), ("Express.js", "express-original"),
        ("Django", "django-plain"), ("Flask", "flask-original"),
        ("FastAPI", "fastapi-plain"), ("Spring Boot", "spring-plain"),
        ("Laravel", "laravel-original"), ("NestJS", "nestjs-plain"),
        (".NET Core", "dotnetcore-plain"),
    ],
    "database": [
        ("PostgreSQL", "postgresql-plain"), ("MySQL", "mysql-plain"),
        ("MongoDB", "mongodb-plain"), ("Redis", "redis-plain"),
        ("SQLite", "sqlite-plain"), ("MariaDB", "mariadb-plain"),
        ("Firebase", "firebase-plain"),
    ],
    "devops": [
        ("Docker", "docker-plain"), ("Kubernetes", "kubernetes-plain"),
        ("AWS", "amazonwebservices-plain-wordmark"), ("Google Cloud", "googlecloud-plain"),
        ("Azure", "azure-plain"), ("Git", "git-plain"),
        ("GitHub Actions", "githubactions-plain"), ("Nginx", "nginx-original"),
        ("Linux", "linux-plain"),
    ],
    "mobile": [
        ("React Native", "react-original"), ("Flutter", "flutter-plain"),
        ("Android", "android-plain"), ("iOS", "apple-original"),
    ],
}


def seed(apps, schema_editor):
    Technology = apps.get_model("accounts", "Technology")
    for category, items in DATA.items():
        for name, icon in items:
            Technology.objects.update_or_create(
                name=name,
                defaults={"category": category, "icon_class": f"devicon-{icon} colored"},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_technology_category'),
    ]

    operations = [
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]