# Generated by Django 6.1 on 2026-10-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_hat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_suit',
            field=models.CharField(choices=[('black', 'Clássico'), ('wine', 'Vinho'), ('navy', 'Azul-Marinho')], default='black', max_length=20),
        ),
    ]
