# Generated by Django 6.1 on 2026-09-17 12:42

import Tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(default=Tasks.models.code_generator, max_length=6, unique=True),
        ),
    ]
