# Generated by Django 6.0.6 on 2026-09-16 14:04

import Tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, validators=[Tasks.models.validate_future_date]),
        ),
    ]
