# Generated by Django 6.1 on 2026-09-30 13:47

import Tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, validators=[Tasks.models.validate_future_date]),
        ),
    ]
