# Generated by Django 6.1 on 2026-10-04 02:42

from itertools import islice

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_project_memberships(apps, schema_editor):
    Project = apps.get_model('Tasks', 'Project')
    ProjectMember = apps.get_model('Tasks', 'ProjectMember')
    database = schema_editor.connection.alias
    project_members = Project.objects.using(database).values_list(
        'pk',
        'owner_id',
        'members__pk',
    ).iterator(chunk_size=1000)

    while True:
        batch = list(islice(project_members, 1000))
        if not batch:
            break

        memberships = [
            ProjectMember(
                project_id=project_id,
                user_id=user_id,
                role='member',
            )
            for project_id, owner_id, user_id in batch
            if user_id is not None and user_id != owner_id
        ]
        if memberships:
            ProjectMember.objects.using(database).bulk_create(
                memberships,
                batch_size=1000,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_project_category_accent_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Líder'), ('member', 'Integrante')], default='member', max_length=10)),
                ('can_create_tasks', models.BooleanField(default=True)),
                ('can_delete_tasks', models.BooleanField(default=False)),
                ('can_edit_tasks', models.BooleanField(default=True)),
                ('can_create_boards', models.BooleanField(default=False)),
                ('can_invite_members', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Tasks.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.RunPython(
            create_existing_project_memberships,
            migrations.RunPython.noop,
        ),
    ]
