# Generated by Django 6.1 on 2026-10-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_can_create_boards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='default_can_create_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_can_delete_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='default_can_edit_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_can_invite_members',
            field=models.BooleanField(default=True),
        ),
    ]
